spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:rds!db-83437ad6-f925-4f4d-8340-f10ad49f12e9

  datasource:
    url: jdbc:postgresql://izza-db.cji28gw0m12f.ap-northeast-2.rds.amazonaws.com:5432/izza
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Lower for dev
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# Optional: Add logging for debugging
logging:
  level:
    io.awspring.cloud.secretsmanager: DEBUG
    org.springframework.boot.context.config: DEBUG