spring:
  config:
    activate:
      on-profile: local
    import: aws-secretsmanager:rds!db-83437ad6-f925-4f4d-8340-f10ad49f12e9

  datasource:
    url: jdbc:postgresql://localhost:15432/izza
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE