# server:
#   servlet:
#     context-path: /prod/api/v1

app:
  base-path: "/prod"

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://izza-db.cji28gw0m12f.ap-northeast-2.rds.amazonaws.com:5432/izza
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:defaultpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Lower for dev
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized